### PR TITLE
Compatibility with GNOME 45

### LINKED ISSUE #16: GNOME 45 support
Extension doesn't currently support GNOME 45 and is marked as Incompatible on [extensions.gnome.org](https://extensions.gnome.org/extension/4630/no-titlebar-when-maximized/).

GNOME 45 is in Arch Linux repos already :)

### PR DESCRIPTION
**Pull request by francescolf**
Fixes #16

### CODE REVIEW

**Comment by MikeWent** [comment]
This works. Tested on GNOME 45.0 Wayland. Thank you!

**Comment by jhpratt** [comment]
Here's another voice confirming that it works as expected!

**Comment by alecdotninja** [comment]
Thank you for @francescolf ! This is now released as [v12](https://extensions.gnome.org/review/47731).

**Comment by alecdotninja** [comment]
Sadly, the version was rejected. I've made an attempt to address the review comments in #19 , but now the extension won't load at all. :disappointed:

**Comment by harpreetsb** [comment]
how long should we wait for this fix?

**Comment by kron4eg** [comment]
> how long should we wait for this fix?

Almost sure that generous donate could speedup things ;) A patch could work too! :)

**Comment by alecdotninja** [comment]
This is finally [available on the GNOME store](https://extensions.gnome.org/review/51373) 🎉

**Pull request merged**
